/* This file is generated by BUSMASTER */
/* VERSION [1.2] */
/* BUSMASTER VERSION [3.2.2] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>
/* End BUSMASTER include header */


/* Start BUSMASTER global variable */
STCAN_MSG tx;
int voltageHVS;
int currentHVS;
int tempHVBat;
/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnTimer_bmsSend_5( );
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER Function Wrapper Prototype  */
/* End BUSMASTER Function Wrapper Prototype  */


/* Start BUSMASTER generated function - OnTimer_bmsSend_5 */
void OnTimer_bmsSend_5( )
{
/* TODO */
voltageHVS= rand()%5 + 548;
currentHVS= rand()%5 + 80;
tempHVBat= rand()%5 + 50;
tx.id=0x12;
tx.dlc=8;
tx.data[0]=voltageHVS >> 8;
tx.data[1]=voltageHVS;
tx.data[2]=currentHVS >> 8;
tx.data[3]=currentHVS;
tx.data[4]=tempHVBat >> 8;
tx.data[5]=tempHVBat;
tx.data[6]=0;
tx.data[7]=0;
SendMsg(tx);
}/* End BUSMASTER generated function - OnTimer_bmsSend_5 */
