/* This file is generated by BUSMASTER */
/* VERSION [1.2] */
/* BUSMASTER VERSION [3.2.2] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>
/* End BUSMASTER include header */


/* Start BUSMASTER global variable */
STCAN_MSG tx;
int tempInv;
int tempMot;
int throttle;
int brake;
/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnTimer_inverterTmr_5( );
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER Function Wrapper Prototype  */
/* End BUSMASTER Function Wrapper Prototype  */


/* Start BUSMASTER generated function - OnTimer_inverterTmr_5 */
void OnTimer_inverterTmr_5( )
{
/* TODO */
tempMot= rand()%5 + 80;
tempInv= rand()%5 + 50;
tx.id=0x22;
tx.dlc=8;
tx.data[0]=tempInv >> 8;
tx.data[1]=tempInv;
tx.data[2]=tempMot >> 8;
tx.data[3]=tempMot;
tx.data[4]=0xFF;
tx.data[5]=0xFF;
tx.data[6]=0xFF;
tx.data[7]=0xFF;
SendMsg(tx);

throttle= rand()%100;
brake= rand()%100;
tx.id=0x24;
tx.dlc=8;
tx.data[0]=throttle;
tx.data[1]=brake;
SendMsg(tx);


}/* End BUSMASTER generated function - OnTimer_inverterTmr_5 */
