/* This file is generated by BUSMASTER */
/* VERSION [1.2] */
/* BUSMASTER VERSION [3.2.2] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>
/* End BUSMASTER include header */


/* Start BUSMASTER global variable */
STCAN_MSG tx;
int tempLVBat;
int tempCoolSys;
/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnTimer_lvsTmr_50( );
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER Function Wrapper Prototype  */
/* End BUSMASTER Function Wrapper Prototype  */


/* Start BUSMASTER generated function - OnTimer_lvsTmr_50 */
void OnTimer_lvsTmr_50( )
{
/* TODO */
tempLVBat= rand()%5 + 50;
tempCoolSys= rand()%5 + 50;
tx.id=0x15;
tx.dlc=8;
tx.data[0]=tempLVBat >> 8;
tx.data[1]=tempLVBat;
tx.data[2]=tempCoolSys >> 8;
tx.data[3]=tempCoolSys;
tx.data[4]=0;
tx.data[5]=0;
tx.data[6]=0;
tx.data[7]=0;
SendMsg(tx);
}/* End BUSMASTER generated function - OnTimer_lvsTmr_50 */
