/* This file is generated by BUSMASTER */
/* VERSION [1.2] */
/* BUSMASTER VERSION [3.2.2] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>
/* End BUSMASTER include header */


/* Start BUSMASTER global variable */
STCAN_MSG tx;
int suspFL;
int suspFR;
int suspBL;
int suspBR;
/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnTimer_suspensionTmr_5( );
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER Function Wrapper Prototype  */
/* End BUSMASTER Function Wrapper Prototype  */


/* Start BUSMASTER generated function - OnTimer_suspensionTmr_5 */
void OnTimer_suspensionTmr_5( )
{
/* TODO */
    
    suspFL= rand()%60;
    suspFR= rand()%60;
    suspBL= rand()%60;
    suspBR= rand()%60;

    tx.id=0x32;
    tx.dlc=8;
    tx.data[0]=suspFL >> 8;
    tx.data[1]=suspFL;
    tx.data[2]=suspFR >> 8;
    tx.data[3]=suspFR;
    tx.data[4]=suspBL >> 8;
    tx.data[5]=suspBL;
    tx.data[6]=suspBR >> 8;
    tx.data[7]=suspBR;
    SendMsg(tx);
}/* End BUSMASTER generated function - OnTimer_suspensionTmr_5 */
